---
author: "Paweł Pechta"
title: "Multinomial LR Model for predicting the outcomes of football matches"
---

```{r}
install.packages("tidyverse")
install.packages("mice")
install.packages("caTools")
```

# Source data import

```{r}
library(tidyverse)

dataset <- dir("source_data", full.names = T) %>% map_df(read_csv) # Import of source data files about 2011/2012 - 2020/2021 seasons

```

# Processing and Exploring Data

```{r}
dataset <- dataset[c(2:10, 12:23)] # Keep only game statistics in dataset
# What means delete of qualitative variables and statistics about betting from source datasets 
```


```{r}
library(mice)
md.pattern(dataset) # Checking for missing values in dataset

dataset <- na.omit(dataset) # Removing empty row

```


```{r}
summary(dataset)

write.csv(dataset, "./dataset.csv", row.names=FALSE) # Export dataframe to csv file
```


```{r}
library(caTools)

set.seed(123)   #  Setting seed to ensure have same random numbers generated
sample = sample.split(dataset,SplitRatio = 0.70) # Splitting the data 70:30 ratio into training and test set
train = subset(dataset,sample == TRUE) 
test = subset(dataset, sample == FALSE)

write.csv(train, "./training/training.csv", row.names = FALSE) # Export training dataframe to csv file
write.csv(test, "./testing/test.csv", row.names = FALSE) # Export test dataframe to csv file
```